services:
  web:
    image: api-banking:latest
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/banking
    ports:
      - '8080:8080'
  postgres:
    image: postgres:15.1-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: banking
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
