services:
  web:
    image: api-banking:latest
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/banking
      - AUTH_URI=http://keycloak.localhost:9000/realms/banking
    ports:
      - '8080:8080'
  postgres:
    image: postgres:15.1-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: banking
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  keycloak:
    image: kc-banking:latest
    hostname: keycloak.localhost
    command:
      - start-dev
      - --import-realm
    environment:
      - KC_HTTP_PORT=9000
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - REALM_NAME=banking
    ports:
      - '9000:9000'
